# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_ros_control_interface/Ros2ControlManager

ros_control_namespace: /

# controller_list:
#   - name: /joint_trajectory_controller
#     action_ns: follow_joint_trajectory
#     type: FollowJointTrajectory
#     default: true
#     joints:
#       - joint_1
#       - joint_2
#       - joint_3
#       - joint_4
#       - joint_5
#       - joint_6



moveit_controller_manager: moveit_ros_control_interface/Ros2ControlManager
moveit_simple_controller_manager:
  controller_names:
    - joint_trajectory_controller
  joint_trajectory_controller:
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6


# moveit_simple_controller_manager:
#   controller_names:
#     - joint_trajectory_controller

#   joint_trajectory_controller:
#     type: FollowJointTrajectory
#     action_ns: follow_joint_trajectory
#     default: true
#     joints:
#       - joint_1
#       - joint_2
#       - joint_3
#       - joint_4
#       - joint_5
#       - joint_6
#     action_ns: follow_joint_trajectory
#     default: true